### ISSUE TITLE
I tried to follow the install instructions but it failed at node seeder.js -i

### ISSUE THREAD

**Issue by skrapi** [AlexanderHildreth/learner-api#3]
I successfully ran` npm install` before this.
Error:
➜ node seeder.js -i
internal/modules/cjs/loader.js:955
  throw err;
  ^

Error: Cannot find module '/home/sylvan/projects/learner-api/seeder.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
    at Function.Module._load (internal/modules/cjs/loader.js:835:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by skrapi** [comment]
This is what I get when I run setup on route-bootcamp


➜ node seeder.js -i

/home/sylvan/projects/learner-api/node_modules/mongoose/lib/connection.js:579
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
    ^
Error [MongooseError]: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at new MongooseError (/home/sylvan/projects/learner-api/node_modules/mongoose/lib/error/mongooseError.js:10:11)
    at NativeConnection.Connection.openUri (/home/sylvan/projects/learner-api/node_modules/mongoose/lib/connection.js:579:11)
    at Mongoose.connect (/home/sylvan/projects/learner-api/node_modules/mongoose/lib/index.js:333:15)
    at Object.<anonymous> (/home/sylvan/projects/learner-api/seeder.js:11:10)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by AlexanderHildreth** [comment]
Have you set your MONGODB_URI env variable in the config.env file?

**Comment by skrapi** [comment]
I did not.
